# Python Pandas

- **Pandas** is a popular Python data analysis tool.

- It provides easy to use and highly efficient data structures.

- These data structures deal with numeric or labeled data, stored in the form of tables.

## Data Structures in Pandas

Two fundamental data structures used in pandas are:

1. **Series:** A 1-D array.

2. **Data Frame:** A 2-D array or two or more Series joined together.

In [1]:
# importing pandas and numpy modules.
import numpy as np
import pandas as pd

### Series in Pandas

- **Series** is a 1-D array, holding data values of a single variable, captured from multiple observations.

- Few examples are:

    - Height of each student, belonging to a Class 'C'.

    - Amount of daily rainfall received at Station 'X', in July 2017.

    - Total sales of a product 'P' in every quarter of 2016.

In [2]:
# Creating Series from python list.
# Height data list.
height_data = [4.3, 3.6, 5.1, 5.7, 6.1, 3.5, 3.9, 4.6]
height_series = pd.Series(height_data, index=['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8'])
height_series

s1    4.3
s2    3.6
s3    5.1
s4    5.7
s5    6.1
s6    3.5
s7    3.9
s8    4.6
dtype: float64

In [3]:
# Creating Series from numpy ndarry.
# Daily Rainfall in Kolkata in July, 2025.
kolkata_july_rainfall = pd.Series(10 * np.random.rand(31), index=[f'day{x}' for x in range(1, 32)])
print(kolkata_july_rainfall.head())
print(kolkata_july_rainfall.tail())

day1    0.436464
day2    2.880478
day3    6.345733
day4    3.535113
day5    0.469975
dtype: float64
day27    6.687831
day28    9.714786
day29    0.615025
day30    5.935020
day31    0.893219
dtype: float64

In [4]:
# Creating Series from Python Dictionary.
# Total Quarterly Sales of in a grocery stores.
sales_data = {
    "Q1": 9000, "Q2": 11000, "Q3": 7800, "Q4": 15000
}

quarter_sales = pd.Series(sales_data)
quarter_sales

Q1     9000
Q2    11000
Q3     7800
Q4    15000
dtype: int64

### DataFrame in Pandas

- A **DataFrame** is 2-D shaped and contains data of different parameters, captured from multiple observations.

- Each observation is represented by a single row, and each parameter by a single column.

- Each column can hold different data type.

- You can think of it like a spreadsheet or SQL table, or a dict of Series objects. 

- Few examples are:

    - Height and Weight of all students, belonging to a Class 'C'.

    - Daily  Rainfall received and Average Temperature of a location 'X', in the year 2017.

*DataFrame can be created from any of the following inputs:*

- From a Dict of 1-D ndarrays, lists, tuples, dicts or series.

- From the list of dictionaries.

- 2-D numpy ndarray.

- A Series.

- Data from spreadsheet (CSV or EXCEL), JSON file, SQL tables, Web Tables etc.

In [5]:
# Creating DataFrame from Dict.

youtube_data = {
    'Channel': ['Code With Harry', 'Jym with Me', 'Explorer Nikk', 'Foodies Club'],
    'Ratings': (3.5, 3.2, 4.5, 4.7),
    'Likes': np.random.randint(1000, 9999, 4)
}
youtube_df = pd.DataFrame(youtube_data)
youtube_df

           Channel  Ratings  Likes
0  Code With Harry      3.5   6050
1      Jym with Me      3.2   7328
2    Explorer Nikk      4.5   6632
3     Foodies Club      4.7   1570

In [6]:
# Creating DataFrame from list of Dictionaries.
books = [
    {'Name': 'The Time Machine', 'Author': 'H. G. Wells', 'Price in $': 2.3},
    {'Name': 'Sapiens', 'Author': 'Yuval Noah Harari', 'Price in $': 5.5},
    {'Name': 'Origin', 'Author': 'Dan Brown', 'Price in $': 7.5},
    {'Name': 'The Imortals of Meluha', 'Author': 'Amish', 'Price in $': np.nan}
]

book_df = pd.DataFrame(books, index = list('abcd'))
book_df

                     Name             Author  Price in $
a        The Time Machine        H. G. Wells         2.3
b                 Sapiens  Yuval Noah Harari         5.5
c                  Origin          Dan Brown         7.5
d  The Imortals of Meluha              Amish         NaN

In [7]:
# Creating DataFrame from 2-D numpy ndarray.
weather_data = np.array([[3.42, 33.2], [2.11, 25.7]])
weather_df = pd.DataFrame(weather_data, index=['Mumbai', 'Bangalore'], 
                          columns=['Average Rainfall', 'Average Temp in C'])
weather_df

           Average Rainfall  Average Temp in C
Mumbai                 3.42               33.2
Bangalore              2.11               25.7

In [8]:
# Creating DataFrame from Series.
quarter_sales = pd.Series({
    "Q1": 9000, "Q2": 11000, "Q3": 7800, "Q4": 15000
}, name='Sales')
quarter_sales_df = pd.DataFrame(quarter_sales)
quarter_sales_df

    Sales
Q1   9000
Q2  11000
Q3   7800
Q4  15000

## Accessing Data

- **Data Access** refers to extracting data present in defined data structures.

- **Pandas** provide utilities like **loc** and **iloc** to get data from a Series, a DataFrame, or a Panel.

### Accessing a Single Value

Individual elements can be accessed by specifying either **index number** or **index value**, inside the square brackets.

In [9]:
z = np.arange(10, 16)
s = pd.Series(z, index=list('abcdef'))
s

a    10
b    11
c    12
d    13
e    14
f    15
dtype: int64

In [10]:
s[2]

/var/folders/8g/rwtnwsq157lgn5m1q5yxdhzm0000gn/T/ipykernel_1265/2635755408.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[2]

np.int64(12)

In [11]:
s['d']

np.int64(13)

In [12]:
# Accessing value using get() method.
s.get(2)

/var/folders/8g/rwtnwsq157lgn5m1q5yxdhzm0000gn/T/ipykernel_1265/4060048473.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s.get(2)

np.int64(12)

In [13]:
s.get('d')

np.int64(13)

#### Accessing a Slice

A Series can be sliced in a way, very similar to slicing a python list.

In [14]:
s[1:4]

b    11
c    12
d    13
dtype: int64

In [15]:
# Elements corresponding to start and end index values are included, when index values are used for slicing.
s['b': 'e']

b    11
c    12
d    13
e    14
dtype: int64

### Accessing DataFrame 

- DataFrame can be accessed as numpy ndarray or using the index and column labels.

In [16]:
# Creating DataFrame from list of Dictionaries.
books = [
    {'Name': 'The Time Machine', 'Author': 'H. G. Wells', 'Price in $': 2.3},
    {'Name': 'Sapiens', 'Author': 'Yuval Noah Harari', 'Price in $': 5.5},
    {'Name': 'Origin', 'Author': 'Dan Brown', 'Price in $': 7.5},
    {'Name': 'The Imortals of Meluha', 'Author': 'Amish', 'Price in $': np.nan},
    {'Name': 'Deep Work', 'Author': 'Cal Newport', 'Price in $': 8.25}
]

book_df = pd.DataFrame(books)
book_df

                     Name             Author  Price in $
0        The Time Machine        H. G. Wells        2.30
1                 Sapiens  Yuval Noah Harari        5.50
2                  Origin          Dan Brown        7.50
3  The Imortals of Meluha              Amish         NaN
4               Deep Work        Cal Newport        8.25

In [17]:
book_df['Author'][2]

'Dan Brown'

In [18]:
book_df.loc[2:]

                     Name       Author  Price in $
2                  Origin    Dan Brown        7.50
3  The Imortals of Meluha        Amish         NaN
4               Deep Work  Cal Newport        8.25

In [19]:
book_df.loc[1:3][['Name', 'Price in $']]

                     Name  Price in $
1                 Sapiens         5.5
2                  Origin         7.5
3  The Imortals of Meluha         NaN

## Knowing a Series

- It is possible to understand a Series better by using **describe** method.

- The method provides details like mean, std, etc. about a series.

In [21]:
rng = np.random.default_rng(seed=100)
temp = pd.Series(28 + 10 * rng.standard_normal(100))
temp.describe()

count    100.000000
mean      28.384464
std        9.756507
min        8.244143
25%       21.110853
50%       28.704215
75%       35.097369
max       50.497678
dtype: float64

## Knowing a DataFrame

Two methods can be used to know about the data, present in a data frame.

    1. info()
    2. describe()

In [24]:
weather_data = pd.DataFrame({
    'location': [f'loc_{idx}' for idx in range(1, 101)],
    'temp': pd.Series(28 + 10 * rng.standard_normal(100)),
    'rain': pd.Series(100 + 50 * rng.standard_normal(100))
})
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  100 non-null    object
 1   temp      100 non-null    float64
 2   rain      100 non-null    float64
dtypes: float64(2), object(1)
memory usage: 2.5+ KB

In [25]:
weather_data.describe()

             temp        rain
count  100.000000  100.000000
mean    30.334848  101.569909
std     10.494699   50.538118
min      8.351542  -20.626487
25%     22.139616   67.638327
50%     29.565317  108.453722
75%     38.067204  134.460426
max     57.888242  234.560434

In [28]:
# You can use include argument to white list data types that has to be included in the result.
weather_data.describe(include=['object'])

       location
count       100
unique      100
top       loc_1
freq          1