# Indexing In Pandas

- **Indexing** refers to labeling data elements of a Series, a Data Frame.

- These labels can be utilized for selecting portion of data from any of the defined data structures.

- A single level index can be set to a data frame, by passing a list of values to either using **index attribute** or **index argument** of DataFrame function.

In [4]:
import pandas as pd
import numpy as np
rng = np.random.default_rng(seed=100)

In [5]:
df = pd.DataFrame(np.random.rand(5,2))
df.index = [ 'row_' + str(i) for i in range(1, 6) ]
df

              0         1
row_1  0.430482  0.514696
row_2  0.526668  0.474214
row_3  0.657145  0.266839
row_4  0.280497  0.423552
row_5  0.063587  0.643842

#### Different choices for indexing

- **.loc** is primarily label based, but may also be used with a boolean array. **.loc** will raise **KeyError** when the items are not found.

- **.iloc** is primarily integer position based **(from 0 to length-1 of the axis)**, but may also be used with a boolean array. **.iloc** will raise **IndexError** if a requested indexer is out-of-bounds, except slice indexers which allow out-of-bounds indexing.

In [6]:
df.loc[['row_1','row_3']]

              0         1
row_1  0.430482  0.514696
row_3  0.657145  0.266839

In [7]:
df.loc[['row_5'], 1]

row_5    0.643842
Name: 1, dtype: float64

In [8]:
df.iloc[:4]

              0         1
row_1  0.430482  0.514696
row_2  0.526668  0.474214
row_3  0.657145  0.266839
row_4  0.280497  0.423552

In [9]:
df.iloc[2:5][1]

row_3    0.266839
row_4    0.423552
row_5    0.643842
Name: 1, dtype: float64

In [10]:
rng = np.random.default_rng(seed=100)
student_ids = [f's{idx}' for idx in range(1, 11)]
student_df = pd.DataFrame({
    'S_ID': student_ids,
    'Height': 170.0 + 25.0 * rng.standard_normal(10),
    'Weight': 75.0 + 12.0 * rng.standard_normal(10)
})
student_df

  S_ID      Height      Weight
0   s1  141.061259  101.915669
1   s2  177.243895   67.662083
2   s3  189.521352   75.566534
3   s4  183.599341   96.050816
4   s5  145.965434   58.944242
5   s6  196.775217   78.906894
6   s7  187.536392   66.730587
7   s8  187.624336   74.762138
8   s9  188.626565   80.697039
9  s10  197.608681   51.826783

#### Boolean Indexing

- The operators are: 
    - **|** for **or**
    - **&** for **and** 
    - **~** for **not**

- These must be grouped by using parentheses. **(df['A'] > 2) & (df['B'] < 3)**.

- Boolean Indexing is used to filter data in the DataFrame.

In [11]:
student_df.loc[student_df['S_ID'].isin(['s1', 's5'])]

  S_ID      Height      Weight
0   s1  141.061259  101.915669
4   s5  145.965434   58.944242

In [12]:
student_df[student_df['S_ID'].isin(['s1', 's5'])]

  S_ID      Height      Weight
0   s1  141.061259  101.915669
4   s5  145.965434   58.944242

In [13]:
student_df.iloc[3:7]

  S_ID      Height     Weight
3   s4  183.599341  96.050816
4   s5  145.965434  58.944242
5   s6  196.775217  78.906894
6   s7  187.536392  66.730587

In [14]:
student_df[student_df['Weight'] < 75]

  S_ID      Height     Weight
1   s2  177.243895  67.662083
4   s5  145.965434  58.944242
6   s7  187.536392  66.730587
7   s8  187.624336  74.762138
9  s10  197.608681  51.826783

In [15]:
student_df[student_df['Height'] > 180][['S_ID', 'Height']]

  S_ID      Height
2   s3  189.521352
3   s4  183.599341
5   s6  196.775217
6   s7  187.536392
7   s8  187.624336
8   s9  188.626565
9  s10  197.608681

In [16]:
# Get the students whose height > 180 and weight < 75.
student_df[(student_df['Height'] > 180) & (student_df['Weight'] < 75)]

  S_ID      Height     Weight
6   s7  187.536392  66.730587
7   s8  187.624336  74.762138
9  s10  197.608681  51.826783

In [17]:
# Get the students whose Height is not greater than 170.
student_df[~(student_df['Height'] > 170)][['S_ID']]

  S_ID
0   s1
4   s5

#### Example: Data Filtering.

**Task 1**

- Create a pandas series named **heights_A** with values: **176.2, 158.4, 167.6, 156.2, and 161.4**. These values represent the heights of 5 students of class A.

- Lebel each student as **s1, s2, s3, s4, and s5**.

- Create another series named **weights_A** with values: **85.1, 90.2, 76.8, 80.4, and 78.9**.These values represent the weights of 5 students of class A.

- Lebel each student as **s1, s2, s3, s4, and s5**.

- Create a dataframe named **df_A**, which holds the heights and weights of 5 students **s1, s2, s3, s4, and s5**.

- Label columns as **Student_height** and **Student_weight** respectively.

- Print the dataframe **df_A**.

**Task 2**

- Fiter the rows of **df_A**, whose **Student_height > 160.0** and **Student_weight < 80.0**, and capture them in another dataframe **df_A_filter1**.

- Print the dataframe **df_A_filter1**.

**Task 3**

- Filter the rows from **df_A**, whose index values end with 5, and capture them in another dataframe **df_A_filter2**.

- Print the dataframe **df_A_filter2**.

In [22]:
# Task 1.
student_labels = [f's{idx}' for idx in range(1, 6)]
heights_A = pd.Series([176.2, 158.4, 167.6, 156.2, 161.4], index = student_labels)
weights_A = pd.Series([85.1, 90.2, 76.8, 80.4, 78.9], index = student_labels)
df_A = pd.DataFrame({
    'Student_height': heights_A,
    'Student_weight': weights_A
}, index = student_labels)

df_A

    Student_height  Student_weight
s1           176.2            85.1
s2           158.4            90.2
s3           167.6            76.8
s4           156.2            80.4
s5           161.4            78.9

In [23]:
# Task 2.
df_A_filter1 = df_A[(df_A['Student_height'] > 160.0) & (df_A['Student_weight'] < 80.0)]
df_A_filter1

    Student_height  Student_weight
s3           167.6            76.8
s5           161.4            78.9

In [24]:
# Task 3.
df_A_filter2 = df_A.loc[df_A.index.str.endswith('5')]
df_A_filter2

    Student_height  Student_weight
s5           161.4            78.9

## Hierarchical indexing (MultiIndex)

- The **MultiIndex** object is the hierarchical analogue of the standard **Index** object which typically stores the axis labels in pandas objects. 

- **MultiIndex** can be thought as an array of tuples where each tuple is unique.

- A **MultiIndex** can be created from :
    - A list of arrays using `MultiIndex.from_arrays()`.
    - An array of tuples using `MultiIndex.from_tuples()`.
    - A crossed set of iterables using `MultiIndex.from_product()`.
    - A DataFrame using `MultiIndex.from_frame()`.

In [ ]:
# MultiIndex created from array.
array_index = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]

mul_indx = pd.MultiIndex.from_arrays(array_index, names=['First', 'Second'])
mul_indx

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['First', 'Second'])

In [ ]:
data = pd.DataFrame(rng.standard_normal(8), index=mul_indx)
data

                     0
First Second
bar   one    -0.992478
      two    -1.405471
baz   one    -0.231096
      two    -0.688847
foo   one     1.515106
      two    -0.603172
qux   one     1.713684
      two    -0.406249

In [ ]:
# MultiIndex created from tuple.
tuple_index = tuple(zip(*array_index))

mul_indx = pd.MultiIndex.from_tuples(tuple_index, name = ['First', 'Second'])
mul_indx

MultiIndex([('bar', 'one'),
            ('bar', 'two'),
            ('baz', 'one'),
            ('baz', 'two'),
            ('foo', 'one'),
            ('foo', 'two'),
            ('qux', 'one'),
            ('qux', 'two')],
           names=['First', 'Second'])

In [ ]:
# MultiIndex created from set of iterables.
iterables = [['Kolkata', 'Delhi', 'Mumbai', 'Chennai'], ['Max', 'Min']]
mul_indx = pd.MultiIndex.from_product(iterables, names=['City', 'Rank'])

rainfall_data = pd.DataFrame(140 + 15 * rng.standard_normal(8), index=mul_indx, columns=['Rainfall'])
rainfall_data

                Rainfall
City    Rank
Kolkata Max   144.071143
        Min   140.597603
Delhi   Max   140.172775
        Min   123.092330
Mumbai  Max   145.020695
        Min   145.758373
Chennai Max   143.567533
        Min   149.321175

In [ ]:
# MultiIndex created from dataframe.
index_df = pd.DataFrame({
    'City': ['Kolkata', 'Kolkata', 'Delhi', 'Delhi', 'Mumbai', 'Mumbai', 'Chennai', 'Chennai'],
    'Rank': ['Max', 'Min', 'Max', 'Min', 'Max', 'Min', 'Max', 'Min']
})
mul_indx = pd.MultiIndex.from_frame(index_df)
data = {
    'Rain': 140 + 15 * rng.standard_normal(8),
    'Temp': 45 + 5 * rng.standard_normal(8)
}

weather = pd.DataFrame(data, index=mul_indx)
weather

                    Rain       Temp
City    Rank
Kolkata Max   127.711317  46.151553
        Min   135.536312  45.537080
Delhi   Max   130.076559  50.369729
        Min   114.437445  51.231770
Mumbai  Max   145.513045  54.064463
        Min   130.467668  42.392580
Chennai Max   138.834192  53.979675
        Min   173.746518  44.343211

#### Accessing Data with MultiIndex

In [ ]:
weather.loc[('Kolkata')]

            Rain       Temp
Rank
Max   127.711317  46.151553
Min   135.536312  45.537080

In [ ]:
weather.loc[('Kolkata', 'Max')]

Rain    127.711317
Temp     46.151553
Name: (Kolkata, Max), dtype: float64

In [ ]:
weather.loc['Kolkata', 'Max']

Rain    127.711317
Temp     46.151553
Name: (Kolkata, Max), dtype: float64

In [ ]:
weather.loc[('Kolkata', 'Min'), 'Temp']

np.float64(45.537079500720935)

In [ ]:
# Sorting the MultiIndex.
weather.sort_index(inplace=True)
weather

                    Rain       Temp
City    Rank
Chennai Max   138.834192  53.979675
        Min   173.746518  44.343211
Delhi   Max   130.076559  50.369729
        Min   114.437445  51.231770
Kolkata Max   127.711317  46.151553
        Min   135.536312  45.537080
Mumbai  Max   145.513045  54.064463
        Min   130.467668  42.392580

In [ ]:
weather.loc['Chennai': 'Kolkata']

                    Rain       Temp
City    Rank
Chennai Max   138.834192  53.979675
        Min   173.746518  44.343211
Delhi   Max   130.076559  50.369729
        Min   114.437445  51.231770
Kolkata Max   127.711317  46.151553
        Min   135.536312  45.537080

In [ ]:
weather.loc[('Delhi', 'Min') : ('Kolkata', 'Max')]

                    Rain       Temp
City    Rank
Delhi   Min   114.437445  51.231770
Kolkata Max   127.711317  46.151553

#### Sorting the MultiIndex

- `sort_index()` is used to sort the index of DataFrame.

In [ ]:
from random import shuffle

idx_tups = [('bar', 'one'), ('bar', 'two'),
               ('baz', 'one'), ('baz', 'two'),
               ('foo', 'one'), ('foo', 'two'),
               ('qux', 'one'), ('qux', 'two')]

# Shuffles the list of tuples
shuffle(idx_tups)

mul_indx = pd.MultiIndex.from_tuples(idx_tups, names = ['first', 'second'])
mul_indx

MultiIndex([('qux', 'one'),
            ('foo', 'two'),
            ('bar', 'two'),
            ('baz', 'two'),
            ('bar', 'one'),
            ('foo', 'one'),
            ('qux', 'two'),
            ('baz', 'one')],
           names=['first', 'second'])

In [ ]:
df = pd.DataFrame({
    'd1': rng.integers(low=-34, high=100, size=8),
    'd2': rng.standard_normal(8)
}, index=mul_indx)

df

              d1        d2
first second
qux   one     62  1.282524
foo   two     41 -0.921824
bar   two     97 -0.339790
baz   two     41 -1.197717
bar   one     50 -1.975586
foo   one     43 -0.018063
qux   two      9  1.582695
baz   one    -10  1.112087

In [ ]:
df.sort_index()

              d1        d2
first second
bar   one     50 -1.975586
      two     97 -0.339790
baz   one    -10  1.112087
      two     41 -1.197717
foo   one     43 -0.018063
      two     41 -0.921824
qux   one     62  1.282524
      two      9  1.582695

In [ ]:
df.sort_index(level=0)

              d1        d2
first second
bar   one     50 -1.975586
      two     97 -0.339790
baz   one    -10  1.112087
      two     41 -1.197717
foo   one     43 -0.018063
      two     41 -0.921824
qux   one     62  1.282524
      two      9  1.582695

In [ ]:
df.sort_index(level=1)

              d1        d2
first second
bar   one     50 -1.975586
baz   one    -10  1.112087
foo   one     43 -0.018063
qux   one     62  1.282524
bar   two     97 -0.339790
baz   two     41 -1.197717
foo   two     41 -0.921824
qux   two      9  1.582695

In [ ]:
df.sort_index(inplace=True)
df

              d1        d2
first second
bar   one     50 -1.975586
      two     97 -0.339790
baz   one    -10  1.112087
      two     41 -1.197717
foo   one     43 -0.018063
      two     41 -0.921824
qux   one     62  1.282524
      two      9  1.582695

## DatetimeIndex in Pandas

- Immutable ndarray-like of **datetime64** data. Represented internally as **int64**.

#### Generating DatetimeIndex.

- `pandas.date_range()`: Returns a fixed frequency DatetimeIndex based on following parameters:
    
    - **start** : Staring Date (str)
    - **end** : Ending Date (str)
    - **Period** : Number of periods to generate (int)
    - **freq** : Date Time frequencies. **B** - Business Day, **D** - Calandar Day, **W** - Weekly, **ME** - Month end, **QE** - Quarter End, **YE** - Year End, **MS** - Month Start, .. etc. (Link: https://pandas.pydata.org/docs/user_guide/timeseries.html#offset-aliases)
    - **tz**: Timezones. ‘Asia/Hong_Kong’. By default,

- `pandas.bdate_range`: Return a fixed frequency DatetimeIndex with business day as the default.

In [ ]:
pd.date_range(start='1/1/2018', end='1/08/2018')

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(
    start=pd.to_datetime("1/1/2018").tz_localize("Europe/Berlin"),
    end=pd.to_datetime("1/08/2018").tz_localize("Europe/Berlin"),
)

DatetimeIndex(['2018-01-01 00:00:00+01:00', '2018-01-02 00:00:00+01:00',
               '2018-01-03 00:00:00+01:00', '2018-01-04 00:00:00+01:00',
               '2018-01-05 00:00:00+01:00', '2018-01-06 00:00:00+01:00',
               '2018-01-07 00:00:00+01:00', '2018-01-08 00:00:00+01:00'],
              dtype='datetime64[ns, Europe/Berlin]', freq='D')

In [ ]:
pd.date_range(start='1/1/2018', periods=8)

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06', '2018-01-07', '2018-01-08'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(end='1/1/2018', periods=8)

DatetimeIndex(['2017-12-25', '2017-12-26', '2017-12-27', '2017-12-28',
               '2017-12-29', '2017-12-30', '2017-12-31', '2018-01-01'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2018-04-24', end='2018-04-27', periods=3)

DatetimeIndex(['2018-04-24 00:00:00', '2018-04-25 12:00:00',
               '2018-04-27 00:00:00'],
              dtype='datetime64[ns]', freq=None)

In [ ]:
pd.date_range(start='1/1/2018', periods=12, freq='ME')

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30', '2018-07-31', '2018-08-31',
               '2018-09-30', '2018-10-31', '2018-11-30', '2018-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
pd.date_range(start='1/1/2018', periods=5, freq='3ME')

DatetimeIndex(['2018-01-31', '2018-04-30', '2018-07-31', '2018-10-31',
               '2019-01-31'],
              dtype='datetime64[ns]', freq='3ME')

In [ ]:
# Business Days.
pd.bdate_range(start='1/1/2018', end='1/08/2018')

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-08'],
              dtype='datetime64[ns]', freq='B')

In [ ]:
# Generate sequences of fixed-frequency dates and time spans.
dti = pd.date_range(start='10/18/2025', periods=3, freq='h')
dti

DatetimeIndex(['2025-10-18 00:00:00', '2025-10-18 01:00:00',
               '2025-10-18 02:00:00'],
              dtype='datetime64[ns]', freq='h')

In [ ]:
# Manipulating and converting date times with timezone information.
dti = dti.tz_localize('UTC')
dti

DatetimeIndex(['2025-10-18 00:00:00+00:00', '2025-10-18 01:00:00+00:00',
               '2025-10-18 02:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='h')

In [ ]:
dti.tz_convert('Asia/Kolkata')

DatetimeIndex(['2025-10-18 05:30:00+05:30', '2025-10-18 06:30:00+05:30',
               '2025-10-18 07:30:00+05:30'],
              dtype='datetime64[ns, Asia/Kolkata]', freq='h')

In [ ]:
from datetime import datetime
# Use DatetimeIndex as Index.
data = pd.Series(rng.integers(low=1, high=20, size=10), index=pd.date_range(start=datetime.now(), periods=10, freq='h'))
data

2025-10-19 20:32:43.738459     3
2025-10-19 21:32:43.738459     9
2025-10-19 22:32:43.738459     8
2025-10-19 23:32:43.738459     5
2025-10-20 00:32:43.738459     6
2025-10-20 01:32:43.738459     6
2025-10-20 02:32:43.738459    14
2025-10-20 03:32:43.738459     8
2025-10-20 04:32:43.738459    14
2025-10-20 05:32:43.738459    14
Freq: h, dtype: int64

#### Example 1:

- Create an Index named **dates** representing a range of dates starting from **1-Sep-2017** to **15-Sep-2017**.

- Print the 3rd element of the created **DateTimeIndex**.

In [ ]:
dates = pd.date_range(start='1-Sep-2017', end='15-Sep-2017')
dates[2]

Timestamp('2017-09-03 00:00:00')

#### Example 2:

- Convert the following date strings into datetime objects **datelist = ['14-Sep-2017', '9-Sep-2017']**.

- Capture the result in the variable **'dates_to_be_searched'** and print it.

In [ ]:
datelist = ['14-Sep-2017', '9-Sep-2017']
dates_to_be_searched = pd.to_datetime(datelist)
dates_to_be_searched

DatetimeIndex(['2017-09-14', '2017-09-09'], dtype='datetime64[ns]', freq=None)

#### Example 3:

- Check if the elements of **dates_to_be_searched** are present in DateTimeIndex, **'date'**, created above.

- Print the output

In [ ]:
dates_to_be_searched.isin(dates)

array([ True,  True])

#### Example 4:

- Create a multi index named **mi_index** of two levels, represented in the following array **arraylist = [['classA'] * 5 + ['classB'] * 5, ['s1', 's2', 's3', 's4', 's5'] * 2]**.

 - Print levels of **mi_index**.

In [ ]:
arraylist = [['classA'] * 5 + ['classB'] * 5, ['s1', 's2', 's3', 's4', 's5'] * 2]
mi_index = pd.MultiIndex.from_product(arraylist)
mi_index.levels

FrozenList([['classA', 'classB'], ['s1', 's2', 's3', 's4', 's5']])