# Data Cleaning using Pandas

- Data Cleaning refers to transformation of raw data to a useful structured form, which is used for further analysis.

- The process includes various steps like dealing with missing values.

- Pandas provide following methods to deal with missing and duplicate data.

    - `dropna()`

    - `isna()`

    - `notna()`

    - `replace()`

    - `fillna()`

    - `drop_duplicates()`

In [121]:
import pandas as pd 
import numpy as np

In [122]:
book_df = pd.DataFrame({
    "Book Title": [
        "Fourth Wing",
        "The Heaven & Earth Grocery Store",
        "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
        "A Court of Thorns and Roses (ACOTAR)",
        "The Wager: A Tale of Shipwreck, Mutiny and Murder",
        "Remarkably Bright Creatures",
        "Lessons in Chemistry",
        "The Woman in Me",
        "Tomorrow, and Tomorrow, and Tomorrow",
        "Missing",
        "Lessons in Chemistry",
        "NA"
    ],
    "Book Author": [
        "Rebecca Yarros",
        "James McBride",
        "James Clear",
        np.nan,
        "David Grann",
        "Shelby Van Pelt",
        "Bonnie Garmus",
        "Britney Spears",
        pd.NA,
        "Colleen Hoover",
        "Bonnie Garmus",
        "NA"
    ],
    "Genre": [
        "Fantasy / Romance",
        "Historical Fiction",
        "Self-Help / Psychology",
        "Fantasy / YA",
        "Nonfiction / History",
        "General Fiction",
        "Historical Fiction / Humor",
        "Memoir / Autobiography",
        np.nan,
        "Romance / Thriller",
        None,
        "Missing"
    ],
    "ISBN number": [
        "978-1649374042",
        "978-0593422030",
        "978-0735211292",
        None,
        "978-0385534260",
        "978-0063204911",
        "Missing",
        pd.NA,
        "978-0778334415",
        "978-1501110368",
        "978-1501110228",
        "NA"
    ],
    "Page Number": [
        528,
        400,
        320,
        419,
        352,
        368,
        np.nan,
        288,
        None,
        384,
        345,
        "NA"
    ],
    "Price in dollar": [
        19.99,
        28.0,
        14.5,
        10.99,
        21.99,
        np.nan,
        16.99,
        32.99,
        18.0,
        "Missing",
        15.67,
        "NA"
    ]
})

book_df

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400,28.0
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320,14.5
3,A Court of Thorns and Roses (ACOTAR),NaN,Fantasy / YA,None,419,10.99
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352,21.99
5,Remarkably Bright Creatures,Shelby Van Pelt,General Fiction,978-0063204911,368,NaN
6,Lessons in Chemistry,Bonnie Garmus,Historical Fiction / Humor,Missing,NaN,16.99
7,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288,32.99
8,"Tomorrow, and Tomorrow, and Tomorrow",<NA>,NaN,978-0778334415,None,18.0
9,Missing,Colleen Hoover,Romance / Thriller,978-1501110368,384,Missing
10,Lessons in Chemistry,Bonnie Garmus,None,978-1501110228,345,15.67
11,NA,NA,Missing,NA,NA,NA

#### `isna()` and `notna()` Methods

- `isna()` detects missing values (**NaN** in numeric arrays, **None** or **NaN** in object arrays, **NaT** in datetimelike) in array-like objects.

- `notna()` detects non-missing values for an array-like object.

In [123]:
book_df.isna()

    Book Title  Book Author  Genre  ISBN number  Page Number  Price in dollar
0        False        False  False        False        False            False
1        False        False  False        False        False            False
2        False        False  False        False        False            False
3        False         True  False         True        False            False
4        False        False  False        False        False            False
5        False        False  False        False        False             True
6        False        False  False        False         True            False
7        False        False  False         True        False            False
8        False         True   True        False         True            False
9        False        False  False        False        False            False
10       False        False   True        False        False            False
11       False        False  False        False        False            False

In [124]:
book_df.notna()

    Book Title  Book Author  Genre  ISBN number  Page Number  Price in dollar
0         True         True   True         True         True             True
1         True         True   True         True         True             True
2         True         True   True         True         True             True
3         True        False   True        False         True             True
4         True         True   True         True         True             True
5         True         True   True         True         True            False
6         True         True   True         True        False             True
7         True         True   True        False         True             True
8         True        False  False         True        False             True
9         True         True   True         True         True             True
10        True         True  False         True         True             True
11        True         True   True         True         True             True

#### `dropna()` Method.

- This method remove missing values.

##### Parameters


**axis: {0 or ‘index’, 1 or ‘columns’}, default 0**

- Determine if rows or columns which contain missing values are removed.

    - 0, or ‘index’ : Drop rows which contain missing values.

    - 1, or ‘columns’ : Drop columns which contain missing value.

    - Only a single axis is allowed.

**how: {‘any’, ‘all’}, default ‘any’**

- Determine if row or column is removed from DataFrame, when we have at least one NA or all NA.

    - ‘any’ : If any NA values are present, drop that row or column.

    - ‘all’ : If all values are NA, drop that row or column.

**subset: column label or sequence of labels, optional**

- Labels along other axis to consider, e.g. if you are dropping rows these would be a list of columns to include.

**inplace: bool, default `False`**

- Whether to modify the DataFrame rather than creating a new one.

**ignore_index: bool, default `False`**

- If `True`, the resulting axis will be labeled 0, 1, …, n - 1.

In [125]:
book_df

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400,28.0
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320,14.5
3,A Court of Thorns and Roses (ACOTAR),NaN,Fantasy / YA,None,419,10.99
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352,21.99
5,Remarkably Bright Creatures,Shelby Van Pelt,General Fiction,978-0063204911,368,NaN
6,Lessons in Chemistry,Bonnie Garmus,Historical Fiction / Humor,Missing,NaN,16.99
7,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288,32.99
8,"Tomorrow, and Tomorrow, and Tomorrow",<NA>,NaN,978-0778334415,None,18.0
9,Missing,Colleen Hoover,Romance / Thriller,978-1501110368,384,Missing
10,Lessons in Chemistry,Bonnie Garmus,None,978-1501110228,345,15.67
11,NA,NA,Missing,NA,NA,NA

In [126]:
book_df.dtypes

Book Title         object
Book Author        object
Genre              object
ISBN number        object
Page Number        object
Price in dollar    object
dtype: object

In [127]:
book_df.dropna(axis=0, how='any')

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400,28.0
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320,14.5
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352,21.99
9,Missing,Colleen Hoover,Romance / Thriller,978-1501110368,384,Missing
11,NA,NA,Missing,NA,NA,NA

In [128]:
# Drop all rows those have missing page number.
book_df.dropna(subset=['Page Number'])

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400,28.0
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320,14.5
3,A Court of Thorns and Roses (ACOTAR),NaN,Fantasy / YA,None,419,10.99
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352,21.99
5,Remarkably Bright Creatures,Shelby Van Pelt,General Fiction,978-0063204911,368,NaN
7,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288,32.99
9,Missing,Colleen Hoover,Romance / Thriller,978-1501110368,384,Missing
10,Lessons in Chemistry,Bonnie Garmus,None,978-1501110228,345,15.67
11,NA,NA,Missing,NA,NA,NA

In [129]:
# Getting the unique values in the field - 'Price in dollar'.
book_df['Price in dollar'].unique()

array([19.99, 28.0, 14.5, 10.99, 21.99, nan, 16.99, 32.99, 18.0,
       'Missing', 15.67, 'NA'], dtype=object)

In [130]:
# Replacing the custom missing values ('NA', 'Missing') with np.nan.
book_df.replace('NA', np.nan, inplace=True)
book_df.replace('Missing', np.nan, inplace=True)
book_df

/var/folders/8g/rwtnwsq157lgn5m1q5yxdhzm0000gn/T/ipykernel_1617/1733655176.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  book_df.replace('NA', np.nan, inplace=True)
/var/folders/8g/rwtnwsq157lgn5m1q5yxdhzm0000gn/T/ipykernel_1617/1733655176.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  book_df.replace('Missing', np.nan, inplace=True)

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528.0,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400.0,28.00
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320.0,14.50
3,A Court of Thorns and Roses (ACOTAR),NaN,Fantasy / YA,None,419.0,10.99
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352.0,21.99
5,Remarkably Bright Creatures,Shelby Van Pelt,General Fiction,978-0063204911,368.0,NaN
6,Lessons in Chemistry,Bonnie Garmus,Historical Fiction / Humor,NaN,NaN,16.99
7,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288.0,32.99
8,"Tomorrow, and Tomorrow, and Tomorrow",<NA>,NaN,978-0778334415,NaN,18.00
9,NaN,Colleen Hoover,Romance / Thriller,978-1501110368,384.0,NaN
10,Lessons in Chemistry,Bonnie Garmus,None,978-1501110228,345.0,15.67
11,NaN,NaN,NaN,NaN,NaN,NaN

In [131]:
book_df.dtypes

Book Title          object
Book Author         object
Genre               object
ISBN number         object
Page Number        float64
Price in dollar    float64
dtype: object

In [132]:
# Droping the missing values in-place.
book_df.dropna(subset=['Book Title', 'Book Author', 'Price in dollar'], inplace=True)
book_df

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528.0,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400.0,28.00
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320.0,14.50
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352.0,21.99
6,Lessons in Chemistry,Bonnie Garmus,Historical Fiction / Humor,NaN,NaN,16.99
7,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288.0,32.99
10,Lessons in Chemistry,Bonnie Garmus,None,978-1501110228,345.0,15.67

In [133]:
# Getting mean, median price of books.
print(f'Mean Price: {book_df['Price in dollar']. mean()}\nMedian Price: {book_df['Price in dollar'].median()}')

Mean Price: 21.447142857142854
Median Price: 19.99

In [134]:
# Fill the missing values with zeros.
book_df.fillna(0)

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528.0,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400.0,28.00
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320.0,14.50
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352.0,21.99
6,Lessons in Chemistry,Bonnie Garmus,Historical Fiction / Humor,0,0.0,16.99
7,The Woman in Me,Britney Spears,Memoir / Autobiography,0,288.0,32.99
10,Lessons in Chemistry,Bonnie Garmus,0,978-1501110228,345.0,15.67

In [ ]:
# Drop Duplicate values based on Book Title and Book Author. Keeping first by default.
book_df.drop_duplicates(subset=['Book Title', 'Book Author'])

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528.0,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400.0,28.00
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320.0,14.50
4,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352.0,21.99
6,Lessons in Chemistry,Bonnie Garmus,Historical Fiction / Humor,NaN,NaN,16.99
7,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288.0,32.99

In [138]:
# Drop Duplicate values based on Book Title and Book Author. Keeping last value.
book_df.drop_duplicates(subset=['Book Title', 'Book Author'], keep='last', 
                        inplace=True, ignore_index=True)

In [139]:
book_df

,Book Title,Book Author,Genre,ISBN number,Page Number,Price in dollar
0,Fourth Wing,Rebecca Yarros,Fantasy / Romance,978-1649374042,528.0,19.99
1,The Heaven & Earth Grocery Store,James McBride,Historical Fiction,978-0593422030,400.0,28.00
2,Atomic Habits: An Easy & Proven Way to Build G...,James Clear,Self-Help / Psychology,978-0735211292,320.0,14.50
3,"The Wager: A Tale of Shipwreck, Mutiny and Murder",David Grann,Nonfiction / History,978-0385534260,352.0,21.99
4,The Woman in Me,Britney Spears,Memoir / Autobiography,<NA>,288.0,32.99
5,Lessons in Chemistry,Bonnie Garmus,None,978-1501110228,345.0,15.67