# Data Aggregation

> **Aggregation:** compute a summary statistic (or statistics) for each group.

- By **“Data Aggregation”** we are referring to a process involving one or more of the following steps:

    - **Splitting** the data into groups based on some criteria.

    - **Applying** a function to each group independently.

    - **Combining** the results into a data structure.

In [160]:
import pandas as pd
import numpy as np
rng = np.random.default_rng(seed=100)

#### Splitting an object into groups

In [161]:
speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0),
        ("bird", "Psittaciformes", 24.0),
        ("mammal", "Carnivora", 80.2),
        ("mammal", "Primates", np.nan),
        ("mammal", "Carnivora", 58),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)

speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [162]:
class_group = speeds.groupby(by = ['class'])
class_group.head()

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [163]:
class_order_group = speeds.groupby(by = ['class', 'order'])
class_order_group.head()

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [164]:
# MultiIndex Groups.
arrays = [
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["doo", "doo", "bee", "bee", "bop", "bop", "bop", "bop"],
    ["one", "two", "one", "two", "one", "two", "one", "two"],
]
mul_indx = pd.MultiIndex.from_arrays(arrays, names=['First', 'Second', 'Third'])
data = pd.DataFrame(np.random.randn(8), index=mul_indx, columns=['Value'])
data

                       Value
First Second Third
bar   doo    one    0.681717
             two    0.454227
baz   bee    one   -0.925525
             two    0.208416
foo   bop    one   -0.997034
             two    0.038365
qux   bop    one   -0.876477
             two    0.903664

In [165]:
data.groupby(by = ['Third']).sum()

          Value
Third
one   -2.117318
two    1.604672

In [166]:
data.groupby(level=2).sum()

          Value
Third
one   -2.117318
two    1.604672

In [167]:
data.groupby(by = ['First', 'Second']).sum()

                 Value
First Second
bar   doo     1.135944
baz   bee    -0.717109
foo   bop    -0.958669
qux   bop     0.027187

#### Aggregation

An aggregation is a GroupBy operation that reduces the dimension of the grouping object

In [168]:
animals = pd.DataFrame(
    {
        "kind": ["cat", "dog", "cat", "dog"],
        "height": [9.1, 6.0, 9.5, 34.0],
        "weight": [7.9, 7.5, 9.9, 198.0],
    }
)
animals

  kind  height  weight
0  cat     9.1     7.9
1  dog     6.0     7.5
2  cat     9.5     9.9
3  dog    34.0   198.0

In [169]:
animals.groupby(by = ['kind']).mean()

      height  weight
kind
cat      9.3    8.90
dog     20.0  102.75

In [170]:
animals.groupby("kind", as_index=False).sum()

  kind  height  weight
0  cat    18.6    17.8
1  dog    40.0   205.5

<section id="built-in-aggregation-methods">
<span id="groupby-aggregate-builtin"></span><h3>Built-in aggregation methods</h3>
<p>Many common aggregations are built-in to GroupBy objects as methods. Of the methods
listed below, those with a <code class="docutils literal notranslate"><span class="pre">*</span></code> do <em>not</em> have an efficient, GroupBy-specific, implementation.</p>
<table class="table">
<colgroup>
<col style="width: 20.0%">
<col style="width: 80.0%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Method</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.any.html#pandas.core.groupby.DataFrameGroupBy.any" title="pandas.core.groupby.DataFrameGroupBy.any"><code class="xref py py-meth docutils literal notranslate"><span class="pre">any()</span></code></a></p></td>
<td><p>Compute whether any of the values in the groups are truthy</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.all.html#pandas.core.groupby.DataFrameGroupBy.all" title="pandas.core.groupby.DataFrameGroupBy.all"><code class="xref py py-meth docutils literal notranslate"><span class="pre">all()</span></code></a></p></td>
<td><p>Compute whether all of the values in the groups are truthy</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.count.html#pandas.core.groupby.DataFrameGroupBy.count" title="pandas.core.groupby.DataFrameGroupBy.count"><code class="xref py py-meth docutils literal notranslate"><span class="pre">count()</span></code></a></p></td>
<td><p>Compute the number of non-NA values in the groups</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.cov.html#pandas.core.groupby.DataFrameGroupBy.cov" title="pandas.core.groupby.DataFrameGroupBy.cov"><code class="xref py py-meth docutils literal notranslate"><span class="pre">cov()</span></code></a> *</p></td>
<td><p>Compute the covariance of the groups</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.first.html#pandas.core.groupby.DataFrameGroupBy.first" title="pandas.core.groupby.DataFrameGroupBy.first"><code class="xref py py-meth docutils literal notranslate"><span class="pre">first()</span></code></a></p></td>
<td><p>Compute the first occurring value in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.idxmax.html#pandas.core.groupby.DataFrameGroupBy.idxmax" title="pandas.core.groupby.DataFrameGroupBy.idxmax"><code class="xref py py-meth docutils literal notranslate"><span class="pre">idxmax()</span></code></a></p></td>
<td><p>Compute the index of the maximum value in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.idxmin.html#pandas.core.groupby.DataFrameGroupBy.idxmin" title="pandas.core.groupby.DataFrameGroupBy.idxmin"><code class="xref py py-meth docutils literal notranslate"><span class="pre">idxmin()</span></code></a></p></td>
<td><p>Compute the index of the minimum value in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.last.html#pandas.core.groupby.DataFrameGroupBy.last" title="pandas.core.groupby.DataFrameGroupBy.last"><code class="xref py py-meth docutils literal notranslate"><span class="pre">last()</span></code></a></p></td>
<td><p>Compute the last occurring value in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.max.html#pandas.core.groupby.DataFrameGroupBy.max" title="pandas.core.groupby.DataFrameGroupBy.max"><code class="xref py py-meth docutils literal notranslate"><span class="pre">max()</span></code></a></p></td>
<td><p>Compute the maximum value in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.mean.html#pandas.core.groupby.DataFrameGroupBy.mean" title="pandas.core.groupby.DataFrameGroupBy.mean"><code class="xref py py-meth docutils literal notranslate"><span class="pre">mean()</span></code></a></p></td>
<td><p>Compute the mean of each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.median.html#pandas.core.groupby.DataFrameGroupBy.median" title="pandas.core.groupby.DataFrameGroupBy.median"><code class="xref py py-meth docutils literal notranslate"><span class="pre">median()</span></code></a></p></td>
<td><p>Compute the median of each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.min.html#pandas.core.groupby.DataFrameGroupBy.min" title="pandas.core.groupby.DataFrameGroupBy.min"><code class="xref py py-meth docutils literal notranslate"><span class="pre">min()</span></code></a></p></td>
<td><p>Compute the minimum value in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.nunique.html#pandas.core.groupby.DataFrameGroupBy.nunique" title="pandas.core.groupby.DataFrameGroupBy.nunique"><code class="xref py py-meth docutils literal notranslate"><span class="pre">nunique()</span></code></a></p></td>
<td><p>Compute the number of unique values in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.prod.html#pandas.core.groupby.DataFrameGroupBy.prod" title="pandas.core.groupby.DataFrameGroupBy.prod"><code class="xref py py-meth docutils literal notranslate"><span class="pre">prod()</span></code></a></p></td>
<td><p>Compute the product of the values in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.quantile.html#pandas.core.groupby.DataFrameGroupBy.quantile" title="pandas.core.groupby.DataFrameGroupBy.quantile"><code class="xref py py-meth docutils literal notranslate"><span class="pre">quantile()</span></code></a></p></td>
<td><p>Compute a given quantile of the values in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.sem.html#pandas.core.groupby.DataFrameGroupBy.sem" title="pandas.core.groupby.DataFrameGroupBy.sem"><code class="xref py py-meth docutils literal notranslate"><span class="pre">sem()</span></code></a></p></td>
<td><p>Compute the standard error of the mean of the values in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.size.html#pandas.core.groupby.DataFrameGroupBy.size" title="pandas.core.groupby.DataFrameGroupBy.size"><code class="xref py py-meth docutils literal notranslate"><span class="pre">size()</span></code></a></p></td>
<td><p>Compute the number of values in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.skew.html#pandas.core.groupby.DataFrameGroupBy.skew" title="pandas.core.groupby.DataFrameGroupBy.skew"><code class="xref py py-meth docutils literal notranslate"><span class="pre">skew()</span></code></a> *</p></td>
<td><p>Compute the skew of the values in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.std.html#pandas.core.groupby.DataFrameGroupBy.std" title="pandas.core.groupby.DataFrameGroupBy.std"><code class="xref py py-meth docutils literal notranslate"><span class="pre">std()</span></code></a></p></td>
<td><p>Compute the standard deviation of the values in each group</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.sum.html#pandas.core.groupby.DataFrameGroupBy.sum" title="pandas.core.groupby.DataFrameGroupBy.sum"><code class="xref py py-meth docutils literal notranslate"><span class="pre">sum()</span></code></a></p></td>
<td><p>Compute the sum of the values in each group</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/api/pandas.core.groupby.DataFrameGroupBy.var.html#pandas.core.groupby.DataFrameGroupBy.var" title="pandas.core.groupby.DataFrameGroupBy.var"><code class="xref py py-meth docutils literal notranslate"><span class="pre">var()</span></code></a></p></td>
<td><p>Compute the variance of the values in each group</p></td>
</tr>
</tbody>
</table>
</section>

In [171]:
animals.groupby(by = ['kind']).max()

      height  weight
kind
cat      9.5     9.9
dog     34.0   198.0

### The `aggregate()` method

- Aggregate using one or more operations over the specified axis.

- It takes a function or list of functions and apply it on each groups of the group-by object.

- It takes positional and keyword arguments as well.

The main function signature is as follows:

`aggregate(func=None, *args, engine=None, engine_kwargs=None, **kwargs)`

In [172]:
# Weather Data Generation.
cities = ['Kolkata', 'Delhi', 'Mumbai', 'Chennai']*3
np.random.shuffle(cities)

weather_data = {
    'City': cities,
    'Rainfall': pd.Series(120 + 30 * rng.standard_normal(12)),
    'Temperature': pd.Series(45 + 12 * rng.standard_normal(12))
}

weather_df = pd.DataFrame(weather_data)
weather_df

       City    Rainfall  Temperature
0   Chennai   85.273511    45.566534
1    Mumbai  128.692674    66.050816
2   Chennai  143.425622    28.944242
3    Mumbai  136.319209    48.906894
4    Mumbai   91.158521    36.730587
5   Chennai  152.130260    44.762138
6     Delhi  141.043670    50.697039
7   Kolkata  141.149204    21.826783
8     Delhi  142.351878    33.090261
9     Delhi  153.130417    28.134347
10  Kolkata  187.289172    42.226854
11  Kolkata  101.655206    36.733835

In [173]:
weather_df.groupby(['City']).aggregate('mean')

           Rainfall  Temperature
City
Chennai  126.943131    39.757638
Delhi    145.508655    37.307216
Kolkata  143.364527    33.595824
Mumbai   118.723468    50.562766

In [174]:
weather_df.groupby(['City']).aggregate(['mean', 'max', 'min', 'std'])

           Rainfall                                    Temperature             \
               mean         max         min        std        mean        max
City
Chennai  126.943131  152.130260   85.273511  36.348461   39.757638  45.566534
Delhi    145.508655  153.130417  141.043670   6.632970   37.307216  50.697039
Kolkata  143.364527  187.289172  101.655206  42.859944   33.595824  42.226854
Mumbai   118.723468  136.319209   91.158521  24.174589   50.562766  66.050816


               min        std
City
Chennai  28.944242   9.373309
Delhi    28.134347  11.857732
Kolkata  21.826783  10.555854
Mumbai   36.730587  14.730084

`apply()` method is used to apply the lambda function.

In [175]:
weather_df.groupby(['City']).aggregate('mean').apply(lambda x: round(x, 2))

         Rainfall  Temperature
City
Chennai    126.94        39.76
Delhi      145.51        37.31
Kolkata    143.36        33.60
Mumbai     118.72        50.56

In [176]:
# Generate Animal Speed Data.
animal_speeds = pd.DataFrame(
    [
        ("bird", "Falconiformes", 389.0),
        ("bird", "Psittaciformes", 24.0),
        ("mammal", "Carnivora", 80.2),
        ("mammal", "Primates", np.nan),
        ("mammal", "Carnivora", 58),
    ],
    index=["falcon", "parrot", "lion", "monkey", "leopard"],
    columns=("class", "order", "max_speed"),
)

animal_speeds

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [177]:
animal_speeds.groupby(by='class')[['max_speed']].aggregate('mean')

        max_speed
class
bird        206.5
mammal       69.1