# Miscellaneous Scripts Examples

In [1]:
import pandas as pd
import numpy as np
rng = np.random.default_rng(seed=100)

In [2]:
df = pd.DataFrame(rng.standard_normal(12).reshape(3, 4),
                  index = ['r1', 'r2', 'r3'],
                  columns=['A', 'B', 'C', 'D'])
df.iloc[:, lambda x : [0,3]]

           A         D
r1 -1.157550  0.543974
r2 -0.961383  0.704973
r3  0.745063 -0.611493

In [3]:
d = pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')
d + pd.Timedelta('1 days 2 hours')

DatetimeIndex(['2017-09-12 02:00:00', '2017-09-14 02:00:00',
               '2017-09-16 02:00:00', '2017-09-18 02:00:00'],
              dtype='datetime64[ns]', freq='2D')

In [4]:
pd.date_range('11-Sep-2017', '17-Sep-2017', freq='2D')

DatetimeIndex(['2017-09-11', '2017-09-13', '2017-09-15', '2017-09-17'], dtype='datetime64[ns]', freq='2D')

In [5]:
data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data, columns=['a', 'b'])
df

   a   b
0  1   2
1  5  10

In [6]:
s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))
'b' in s

True

In [7]:
df = pd.DataFrame({'A':[34, 78, 54], 'B':[12, 67, 43]}, index=['r1', 'r2', 'r3'])
df.loc['r4'] = [67, 78]

df

     A   B
r1  34  12
r2  78  67
r3  54  43
r4  67  78

In [8]:
idx = [ 'r1', 'r2', 'r3', 'row4', 'row5', 'row6', 'r7', 'r8', 'r9', 'row10']
data = rng.integers(1, 100, 20).reshape(10, 2)
df = pd.DataFrame(data, index=idx, columns=['A', 'B'])
df

        A   B
r1     32  63
r2     15  58
r3     57  60
row4   77  53
row5   72  99
row6   13  50
r7     13  77
r8     15  49
r9     23  99
row10  43  97

In [9]:
g = df.groupby(df.index.str.len())
g.value_counts()

   A   B
2  13  77    1
   15  49    1
       58    1
   23  99    1
   32  63    1
   57  60    1
4  13  50    1
   72  99    1
   77  53    1
5  43  97    1
Name: count, dtype: int64

In [10]:
g.filter(lambda x: len(x) > 1)

       A   B
r1    32  63
r2    15  58
r3    57  60
row4  77  53
row5  72  99
row6  13  50
r7    13  77
r8    15  49
r9    23  99

In [11]:
g.aggregate({'A':len, 'B':np.sum})

/var/folders/8g/rwtnwsq157lgn5m1q5yxdhzm0000gn/T/ipykernel_2711/2751139407.py:1: FutureWarning: The provided callable <function sum at 0x10e8d62a0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  g.aggregate({'A':len, 'B':np.sum})

   A    B
2  6  406
4  3  202
5  1   97

In [12]:
s = pd.Series([89.2, 76.4, 98.2, 75.9], index=list('abcd'))
print(s[['c', 'a']])

c    98.2
a    89.2
dtype: float64

In [13]:
data = [{'a': 1, 'b': 2}, {'a': 5, 'b': 10, 'c': 20}]
df = pd.DataFrame(data)
df

   a   b     c
0  1   2   NaN
1  5  10  20.0